//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager_V1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mapa
    {
        public int BazaID { get; set; }
        public int KorisnikID { get; set; }
        public string Title { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string URL { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateExpires { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
